### PR TITLE
story/improve-webapi

### PR DESCRIPTION
**Pull request by fredbelotte**

### CODE REVIEW

**Comment by fredbelotte** [comment]
let me know when ready?

**Comment by Alex-Roff** [comment]
Complete classes need to be passed into REST instead of the foreign keys to provide more complete information. We will make a new comment once a pull is needed.

**Comment by fredbelotte** [comment]
sounds good sir.

**Comment by kenbuise** [comment]
we're good to merge Fred

**Comment by fredbelotte** [comment]
all done!

**Pull request merged**
