### PR TITLE
story/services-client-solution

### PR DESCRIPTION
**Pull request by SmokedEel**
Merging my branch so that when business logic and rest is ready, I can start pulling data on my end.

### CODE REVIEW

**Comment by fredbelotte** [comment]
change title to branch name.

**Comment by SmokedEel** [comment]
It's been changed

**Comment by fredbelotte** [comment]
is this ready?

**Comment by SmokedEel** [comment]
Yes fred, this is ready.

**Comment by SmokedEel** [comment]
I'm going to continue working on this branch, I take back my previous comment.

**Comment by fredbelotte** [comment]
come on now, you need to tell me when. :)

**Comment by SmokedEel** [comment]
sorry @fredbelotte , I was waiting to merge to master but I went a different way to grab my rest service.

**Comment by SmokedEel** [comment]
@fredbelotte the branch is ready to merge, You can merge whenever possible.

**Comment by fredbelotte** [comment]
all done!

**Comment by SmokedEel** [comment]
Thank you!

**Pull request merged**
