### PR TITLE
story/startup logic solution

### PR DESCRIPTION
**Pull request by Alex-Roff**
Business logic need to handle exceptions for all incoming and outgoing information. SOAP connections will need to transfer information from the data access

### CODE REVIEW

**Comment by Alex-Roff** [comment]
All ready for pull and merge to master

**Comment by fredbelotte** [comment]
you need to fix this.

**Comment by Alex-Roff** [comment]
New code added, ready for a pull and merge.

**Comment by fredbelotte** [comment]
still not fixed.

**Comment by Alex-Roff** [comment]
Fixed the conflict.

**Comment by fredbelotte** [comment]
all done!

**Pull request merged**
