### PR TITLE
Story/filters and liberate conn

### PR DESCRIPTION
**Pull request by fredbelotte**
on behalf of @kenbuise

### CODE REVIEW

**Comment by fredbelotte** [comment]
way to go!

**Comment by fredbelotte** [comment]
make sure you are keeping your branch updated.

**Comment by fredbelotte** [comment]
how is it going?

**Comment by kenbuise** [comment]
i'm going to scrap this branch & start a new one :))))

**Comment by fredbelotte** [comment]
is this branch still live?

**Comment by kenbuise** [comment]
no this isn't active anymore

**Pull request closed without merging**
