### PR TITLE
Fixed text on the main screen

### PR DESCRIPTION
**Pull request by fredbelotte**
@SmokedEel

### CODE REVIEW

**Comment by fredbelotte** [comment]
let's keep these fixes rolling.

**Comment by SmokedEel** [comment]
Good to go @fredbelotte !

**Comment by SmokedEel** [comment]
Wait wait wait

**Comment by SmokedEel** [comment]
Okay NOW I'm good haha.

**Comment by fredbelotte** [comment]
all set!

**Pull request merged**
