### PR TITLE
story/setup-client-solution-n

### PR DESCRIPTION
**Pull request by SmokedEel**
This branch's purpose is to show the additions to the UI that have been added.  Certain areas have been deleted, and now there are two views which will show information on the UI for apartment housing.

### CODE REVIEW

**Comment by fredbelotte** [comment]
let me know when this is ready.

**Comment by SmokedEel** [comment]
Ready to go sir!

**Comment by fredbelotte** [comment]
you are still committing?

**Comment by SmokedEel** [comment]
I'm all good

**Comment by fredbelotte** [comment]
all done!

**Pull request merged**
